import FormHome from "@/components/Form/form";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Timer-Next",
  description: "Generated by create next app",
};

export  default function Home() {
  return (
   <FormHome />
  )
}
